# Relation between two Objects

string    object_id1                                # relation's first operand
string    object_id2                                # relation's second operand
float32[] num_value                                 # relation's numeric values
string[]  text_value                                # relation's text values
float32[] confidence                                # relation's confidences
